[project]
name = "data-science-ii-96085"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "ipython>=9.17.1",
    "matplotlib>=3.11.1",
    "nbformat>=5.11.1",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "psycopg2-binary>=2.9.12",
    "pyngrok>=8.1.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "robyn>=0.88.0",
    "scikit-learn>=1.9.1",
    "spicy>=0.16.0",
    "sqlalchemy>=2.0.51",
    "statsmodels>=0.15.0",
]

